### ISSUE TITLE
Secret Operator/TLS improvements

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/roadmap#18]
```[tasklist]
### Tasks
- [x] Auto Rotate CA
- [ ] https://github.com/stackabletech/secret-operator/issues/159
- [ ] https://github.com/stackabletech/secret-operator/issues/93
```
