### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/roadmap#25]
- Lifetime of auto-generated Certificate Authorities (CA) is now set to 1 year
- Secret Operator now logs all issues secrets
- Druid: Extension handling for Druid has been improved
- Druid BREAKING: The database configuration has been moved out of the CRD into a Secret
- BREAKING change: OpenShift now uses the namespace `stackable-operators` in the SecretClass `tls`
- An example Rego ruleset for HDFS which is also part of our new [end-to-end security demo
](https://docs.stackable.tech/home/nightly/demos/end-to-end-security)
- Airflow: DAGs can now be modularized
- NiFi: Supports specifying custom TLS SecretClass
- ZooKeeper: K8s Admins can override the ZNode path
- OpenPolicyAgent: We now support audit/decision logging
- Hive BREAKING: The database configuration has been moved out of the CRD into a Secret

and a long list of smaller improvements and bug fixes...

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/secret-operator/issues/358
- [ ] https://github.com/stackabletech/secret-operator/issues/348
- [ ] https://github.com/stackabletech/druid-operator/issues/490
- [ ] https://github.com/stackabletech/issues/issues/498
- [ ] https://github.com/stackabletech/issues/issues/523
- [ ] https://github.com/stackabletech/airflow-operator/issues/326
- [ ] https://github.com/stackabletech/nifi-operator/issues/499
- [ ] https://github.com/stackabletech/zookeeper-operator/issues/681
- [ ] https://github.com/stackabletech/opa-operator/issues/422
- [ ] https://github.com/stackabletech/druid-operator/issues/352
- [ ] https://github.com/stackabletech/hive-operator/issues/148
```
